### ISSUE TITLE
mat-header references wrong icon library.

### ISSUE THREAD

**Issue by mwinters-stuff** [expandjs/mat-header-panel#1]
For the hamburger menu - the navigation library of icons is not loaded. Thus the button never appears.

It would be nice to be able to provide a "custom icon" for the hamburger, so we can use custom limited set of icons..

**Comment by Pupix** [comment]
That's rather strange. Are you using it inside a [`mat-drawer-panel`](https://github.com/expandjs/mat-drawer-panel)? That's when it shows up (it's just a shortcut for a generic app structure with a nav drawer), otherwise you can use a simple [`mat-icon-button`](https://github.com/expandjs/mat-icon-button) and set it up however you want.

Cheers!

**Comment by mwinters-stuff** [comment]
Yep, inside the drawer-panel, It used to work on 0.9.8 and now it doesn't. I don't include the mat-icons library anywhere by default as I have created my own library with just the 10 icons I have used..

**Comment by mwinters-stuff** [comment]
I will have to try again - the code when I look at it now includes the navigation icons - maybe 0.9.8 was the problem..

**Comment by Pupix** [comment]
Did you figure it out?

**Comment by mwinters-stuff** [comment]
I have not had time tonight to look at it..

On 22 September 2015 at 20:43, Robert Manolea notifications@github.com
wrote:

> Did you figure it out?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/expandjs/mat-header-panel/issues/1#issuecomment-142215254
> .

## 

_Mathew Winters_
_See my other apps_
_https://play.google.com/store/apps/developer?id=Mathew+Winters
https://play.google.com/store/apps/developer?id=Mathew+Winters_

**Comment by mwinters-stuff** [comment]
The icon is being loaded, but the burger button is not displaying when the drawer hides! This is my code extract..

```
    <mat-drawer-panel>
        <mat-drawer id="drawer" target="content" animatable narrow="{{_drawerNarrow}}">
          <mat-header id="drawerToolbar" raised>
            <mat-icon-button icon="custom-icons:home" on-xp-activate="_onHome"></mat-icon-button>
            <div extended></div>
          </mat-header>
          <mat-list id="sensoritems" selected-attribute="route" on-xp-select="_onListSelect">
            <mat-sublist hidden$="{{_isNotLoaded(_menuSensors)}}" label="Sensors" collapsible >
              <template is="dom-repeat" items="{{_menuSensors}}" as="menuSensor" filter="_filterNoDewpoint" sort="_sortSensors">
                <mat-item id="[[menuSensor.id]]" route$="{{_getSensorRoute(menuSensor.id)}}" label="[[menuSensor.name]]" selectable is-sensor="true"></mat-item>
              </template>
            </mat-sublist>

            <template is="dom-repeat" items="{{_menuNodeSensors}}" as="menuNode">
              <mat-sublist id="[[menuNode.id]]" label="[[menuNode.caption]]" collapsible collapsed>
                <template is="dom-repeat" items="{{menuNode.sensors}}" as="menuNodeSensor">
                  <mat-item id="[[menuNodeSensor.id]]" route$="{{_getNodeSensorRoute(menuNodeSensor.id)}}" label="[[menuNodeSensor.caption]]" selectable is-sensor="false"></mat-item>
                </template>
              </mat-sublist>
            </template>
          </mat-list>
        </mat-drawer>

        <mat-header-panel id="content">
          <mat-header>

            <div>Sensor Net</div>
            <div class="flex">
              <mat-spinner id="progress"></mat-spinner>
            </div>
            <mat-icon-button icon="custom-icons:settings" on-xp-activate="_onSettings"></mat-icon-button>
            <mat-icon-button icon="custom-icons:exit-to-app" on-xp-activate="_onLogout"></mat-icon-button>
          </mat-header>

          <mat-content>
            <!-- id="content"> -->
... content here in mat-pages
        </mat-content>

        </mat-header-panel>
      </mat-drawer-panel>


```

**Comment by Pupix** [comment]
Thanks for the snippet!

There seems to be a bower caching problem. To fix this you should do the following:
1. delete your `bower_components` directory
2. clean bower's cache using `bower cache clean`
3. reinstall your components using `bower install`

**Comment by mwinters-stuff** [comment]
Hi..

Thanks - I kinda feel a little stupid.. I had deleted bower_components but not the cache - as I was having the problem on two different computers - I thought it was something in the component. 

Have a good day.
Mathew.
